### ISSUE TITLE
Add "Create Dataset/Project" Node

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-omero#18]
Files always need to be added to a dataset on the omero server. We need the ability to create a dataset or project on the omero server from a workflow using a node.

Required features:
- [x] Uses OMERO connection port
- [x] Create dataset
- [x] Create project

Added as _Create Omero Folder_ node to the rc branch

**Comment by dietzc** [comment]
* [ ] Add "Delete" option.

**Comment by gab1one** [comment]
How about we call this node **OMERO Manager**?

**Comment by dietzc** [comment]
I think `OMERO Manager` is too general and nobody knows from the name what it actually does. Therefore I vote for `OMERO Create` and `OMERO Delete`?
