### ISSUE TITLE
Create Download from OMERO node

### ISSUE THREAD

**Issue by gab1one** [knime-ip/knip-omero#19]
## Goals:

- [ ] Download files from OMERO Server
- [ ] Takes list of URIs from input port
- [ ] Outputs URIs of local copies

**Comment by dietzc** [comment]
Why do we need this node? Can't we use the default "Download" node from Remote Files if we need such a node? Isn't the Image Reader enough?

**Comment by gab1one** [comment]
No longer needed, I built support for the normal Download node instead.
