### ISSUE TITLE
OMERO crashes KNIME when opened

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip-omero#3]
see https://tech.knime.org/forum/knime-image-processing/omero-reader-crashes-knime.
One first attempt would be to update the OMERO libs to the latest version and see if KNIME still crashes.

**Comment by ehrenfeu** [comment]
Would it somehow be feasible to have different versions of the OMERO libs available? As Kai mentioned in the above linked forum posting, we're currently still on the OMERO 5.1.x series (although this is hopefully only a matter of a few weeks), and I know from personal experience that there are quite some other sites out there that do not necessarily always upgrade directly to the latest release...

Cheers
Niko

**Comment by dietzc** [comment]
hi @ehrenfeu,

we will try to offer more versions of omero (not only the latest) after we figured out whats going wrong with the current integration. Do you know the compatibility policy of OMERO? 5.y.* is compatible to any other 5.y.*?

Best,

Christian

PS: We are also planning a "thinner" integration of OMERO, i.e. one without Insight as the UI.

**Comment by ctrueden** [comment]
> Do you know the compatibility policy of OMERO? 5.y.* is compatible to any other 5.y.*?

Yep.

**Comment by gab1one** [comment]
I fixed the basic connection problems in #4 but there is still many ways to crash KNIME using this node:
- e.g If you have several OMERO reader nodes and try to open the dialog of the second node after you opened the dialog of the first

**Comment by gab1one** [comment]
I fixed the basic connection problems in #4 but there is still many ways to crash KNIME using this node:
- e.g If you have several OMERO reader nodes and try to open the dialog of the second node after you opened the dialog of the first

It looks like there are some weird multi-threading problems happening.
